### ISSUE TITLE
dydx v4 setup issue

### ISSUE THREAD

**Issue by layhau** [junta/tradingview-alert-connector#22]
Hi, thanks for making updates for dydx v4, much appreciated! I'm trying to set it up now but facing some issues, i tried following the instruction for .env file variables setup and noticed you mentioned for dydx v4 only mnemonic(seed) phrase is required, i supposed we need to include wallet address too, no? By the way I noticed dydx v4 has 2 addresses, one is standard ETH address and the other one is dydx chain address, do we need to include any of these? I tried both but getting error message: "Error on getting account data". Thanks for your great help and good work in advance, cheers!

**Comment by junta** [comment]
hey I've fixed the issue "Error on getting account data" and pushed a new version
Could you deploy the latest version and try again? it should work now
https://tv-connector.gitbook.io/docs/setup/faq#how-to-deploy-the-latest-version-of-the-tool

also, you don't need to provide any wallet addresses.
It's derived from mnemonic automatically.

**Comment by layhau** [comment]
hi i tried again, with just mnemonic(seed) phrase for required variables, which i obtained from dydx v4 "export secret phrase", it's basically a series of 24 words with space separated, right? but it doesn't seem to work, i'm still getting error "Error on getting account data".

**Comment by layhau** [comment]
just tested, get message below:
dYdX v3 Account Ready:false, dYdX v4 Account Ready:false, Perpetual Protocol Account Ready:false, GMX Account Ready:undefined

**Comment by junta** [comment]
It works well on my end.
Have you deposited your collateral(USDC)?

**Comment by layhau** [comment]
brilliant, it worked now! thanks a lot!!
